parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Security\KeycloakAuthenticator:
        arguments:
            $serverUrl: '%env(KEYCLOAK_SERVER_URL)%'
            $publicUrl: '%env(KEYCLOAK_PUBLIC_URL)%'
            $realm: '%env(KEYCLOAK_REALM)%'
            $clientId: '%env(KEYCLOAK_CLIENT_ID)%'
            $clientSecret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            $redirectUri: '%env(KEYCLOAK_REDIRECT_URI)%'
